config/routes.rb
Paper::Application.routes.draw do
  
  namespace :admin do 
    resources :users
    resources :galleries do
      member { post :reindex }
    end
  end

  resources :posts do
    member { post :publish }
  end
  
  resources :images
  resources :comments

  devise_for :users, :controllers => { :registrations => "accounts" }
  
  devise_scope :user do
    get    "/signup" => "accounts#new",             :as => :signup
    get    "/login"  => "devise/sessions#new",      :as => :login
    delete "/logout" => "devise/sessions#destroy",  :as => :logout
  end
  
  root :to => "posts#index"
end

app/models/comment.rb
# a comment's default privacy is public
# a reply to a private comment is always private
# a private comment cannot become public (maybe change in the future)
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  include Paper::Markdown
  include Paper::Privacy
  
  markdownifies(:markdown => :html)
  
  before_validation :set_commentable, :on => :create
  before_validation :set_path,        :on => :create
  before_validation :set_visible_to,  :on => :create
  
  before_save  :inherit_privacy
  after_save   :pass_down_privacy
  
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  belongs_to :parent, :class_name => "Comment"
  
  has_many :comments, :foreign_key => :parent_id
  
  validates_presence_of :user_id, :commentable_id, :commentable_type, :path, :visible_to
  validates_presence_of :body
  
  field :path,       :type => Array
  field :visible_to, :type => Array,    :default => [ ]
  field :deleted_at, :type => DateTime, :default => nil
  
  alias_method :body, :markdown
  
  def self.visible_to(user)
    if user
      any_of({ :privacy => Paper::PRIVACY[:public] }, { :visible_to => [ user.id ] })
    else
      where(:privacy => Paper::PRIVACY[:public])
    end
  end
  
  def owned_by?(u)
    u && u == self.user
  end
  
  def can_delete?(u)
    !deleted? && (owned_by?(u) || u.has_role?(:delete_comments))
  end
  
  def deleted?
    !!self.deleted_at
  end
  
  def has_comments?(include_deleted = false)
    if include_deleted
      self.comments.count > 0
    else
      self.comments.where(:deleted_at => nil).count > 0
    end
  end
  
  def delete!
    update_attribute(:deleted_at, Time.now)
  end
  
  protected
    
    # before_validation :on => :create
    # if there is a parent, set the commentable
    # to the parent's commentable
    def set_commentable
      if self.parent
        self.commentable = self.parent.commentable
      end
    end
  
    # before_validation :on => :create
    # the path is a list of ids from the root
    # to this node which includes this node
    def set_path
      if self.parent
        self.path = self.parent.path + [ self.id ]
      else
        self.path = [ self.id ]
      end
    end
    
    # before_validation, :on => :create
    # set the default list of users who can 
    # view this comment
    # a comment is always visible to the owner
    # a comment is always visible to the commentable owner
    # a comment is always visible to the parent comment owner
    def set_visible_to
      
      if self.user
        self.visible_to << self.user.id
      end
      
      if self.commentable
        self.visible_to |= [ self.commentable.user.id ]
        if self.parent
          self.visible_to |= [ self.parent.user.id ]
        end
      end
    end
    
    # a comment is always visible to the owners of child comments
    # set privacy to private if parent or commentable is private
    def inherit_privacy
      if parent
        parent.visible_to |= [ self.user_id ]
        parent.save
      end
      
      if self.parent.try(:private?) || self.commentable.try(:private?)
        self.private!
      end
    end
    
    # after_save
    # if our privacy has changed to private, set children to private
    def pass_down_privacy
      if self.changes.has_key?('privacy') && self.private?
        self.comments.each { |c| c.private! }
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :find_comment, :except => :create
  
  def create
    @comment = Comment.new((params[:comment] || { }).merge(:user => current_user))
    if @comment.save
      redirect_to(polymorphic_path(@comment.commentable, :anchor => @comment.id))
    else
      Rails.logger.info("@comment.errors: #{@comment.errors.full_messages.inspect}")
    end
  end
  
  def destroy
    @comment.delete!
    flash[:notice] = t("comments.deleted")
    redirect_to(polymorphic_path(@comment.commentable))
  end
  
  protected 
  
    def find_comment
      @comment = Comment.find(params[:id])
    rescue Mongoid::Errors::DocumentNotFound
      redirect_to(posts_path)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_date(comment)
    comment.created_at.in_time_zone.strftime("%B %d, %Y &mdash; %H:%M %p %Z").html_safe
  end
end

app/views/comments/_actions.html.erb
<% css = "reply" %>
<% if parent.is_a?(Comment) %>
  <% css << " invisible" %>
<% end %>

<% if parent.is_a?(Comment) %>
  <% if user_signed_in? %>
    <%= link_to(t("reply"), new_comment_path, :class => "reply-link", :id => "reply_link_#{parent.id}", 'data-form-id' => "reply_form_#{parent.id}") %>
    <% if parent.can_delete?(current_user) %>
      <%= link_to(t('delete'), comment_path(parent), :class => 'delete-link', 'data-method' => 'delete', 'data-confirm' => t('comments.delete.confirm')) %>
    <% else %>
      &nbsp;
    <% end %>
  <% else %>
    <%= link_to(t("sign_in_to_reply"), new_user_session_path) %>
  <% end %>
<% end %>

<%= form_for Comment.new, :html => { :class => "form #{css}", :id => "reply_form_#{parent.id}" } do |form| %>
  <% if !parent.is_a?(Comment) %>
    <%= form.hidden_field :commentable_id,   :value => parent.id %>
    <%= form.hidden_field :commentable_type, :value => parent.class.name %>
  <% else %>
    <%= form.hidden_field :parent_id, :value => parent.id %>
  <% end %>
  <div class="field privacy">
    <div class="label"><%= form.label(:privacy, t('privacy')) %></div>
    <div class="select"><%= form.select(:privacy, Paper::PRIVACY) %></div>
    <div class="info">
      <%= link_to("?", comments_path, :class => "info-link", 'data-id' => parent.id) %>
    </div>
    <div class="explain">
      <% if parent.is_a?(Post) %>
        <ul>
          <li><strong><%= t('doc.comment.post_reply.public.term') %></strong>: <%= t('doc.comment.post_reply.public.meaning') %></li>
          <li><strong><%= t('doc.comment.post_reply.private.term') %></strong>: <%= t('doc.comment.post_reply.private.meaning') %></li>
        </ul>
      <% else %>
        <ul>
          <li><strong><%= t('doc.comment.comment_reply.public.term') %></strong>: <%= t('doc.comment.comment_reply.public.meaning') %></li>
          <li><strong><%= t('doc.comment.comment_reply.private.term') %></strong>: <%= t('doc.comment.comment_reply.private.meaning') %></li>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="field">
    <div class="textarea"><%= form.text_area(:markdown, :rows => 8, :cols => 70) %></div>
  </div>
  <div class="actions">
    <% if parent.is_a?(Comment) %>
      <%= link_to(t('cancel'), new_comment_path, :class => "cancel", 'data-form-id' => "reply_form_#{parent.id}", 'data-link-id' => "reply_link_#{parent.id}") %>
    <% end %>
    <% if parent.is_a?(Comment) %>
      <%= form.submit(t('save')) %>
    <% else %>
      <%= form.submit(t('reply')) %>
    <% end %>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<% unless comment.deleted? && !comment.has_comments? %>
  <a name="<%= comment.id %>"></a>
  <div class="comment" data-id="<%= comment.id %>" data-parent-id="<%= comment.parent.try(:id) %>">
    <%= link_to("-", comments_path, :class => "comment-collapse", 'data-collapsed' => false) %>
    <div class="comment-user">
      <% if comment.deleted? %>
        <span class="deleted"><%= t('comments.deleted_placeholder') %></span>
      <% else %>
        <% if comment.user %>
          <span class="name"><%= comment.user.name %></span>
        <% else %>
          <span class="deleted"><%= t('comments.user_deleted_placeholder') %></span>
        <% end %>
      <% end %>
    </div>
    <div class="comment-date">
      <%= comment.deleted? ? "&nbsp;".html_safe : comment_date(comment) %>
    </div>
    <div class="collapsable">
      <div class="comment-body">
        <%= (comment.deleted? ? "<p></p>" : comment.html).html_safe  %>
      </div>
      <%= render(:partial => "comments/actions", :locals => { :parent => comment }) %>
      <% if comment.has_comments? %>
        <%= render(:partial => "comments/comments", :locals => { :parent => comment }) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<div class="comments">
  <%= render(:partial => "comments/comment", :collection => parent.comments.visible_to(current_user).order_by([:created_at, :desc])) %>
</div>

app/views/comments/_reply.html.erb
<% css = "reply" %>
<% if parent.is_a?(Comment) %>
  <% css << " hidden" %>
<% end %>

<% if parent.is_a?(Comment) %>
  <% if user_signed_in? %>
    <%= link_to(t("reply"), new_comment_path, :class => "reply-link", :id => "reply_link_#{parent.id}", 'data-form-id' => "reply_form_#{parent.id}") %>
    <% if parent.can_delete?(current_user) %>
      <%= link_to(t('delete'), comment_path(parent), :class => 'delete-link', 'data-method' => 'delete', 'data-confirm' => t('comments.delete.confirm')) %>
    <% else %>
      &nbsp;
    <% end %>
  <% else %>
    <%= link_to(t("sign_in_to_reply"), new_user_session_path) %>
  <% end %>
<% end %>

<%= form_for Comment.new, :html => { :class => "form #{css}", :id => "reply_form_#{parent.id}" } do |form| %>
  <% if parent.is_a?(Post) %>
    <%= form.hidden_field :post_id, :value => parent.id %>
  <% else %>
    <%= form.hidden_field :parent_id, :value => parent.id %>
  <% end %>
  <div class="field privacy">
    <div class="label"><%= form.label(:privacy, t('privacy')) %></div>
    <div class="select"><%= form.select(:privacy, Paper::PRIVACY) %></div>
    <div class="info">
      <%= link_to("?", comments_path, :class => "info-link", 'data-id' => parent.id) %>
    </div>
    <div class="explain">
      <% if parent.is_a?(Post) %>
        <ul>
          <li><strong><%= t('doc.comment.post_reply.public.term') %></strong>: <%= t('doc.comment.post_reply.public.meaning') %></li>
          <li><strong><%= t('doc.comment.post_reply.private.term') %></strong>: <%= t('doc.comment.post_reply.private.meaning') %></li>
        </ul>
      <% else %>
        <ul>
          <li><strong><%= t('doc.comment.comment_reply.public.term') %></strong>: <%= t('doc.comment.comment_reply.public.meaning') %></li>
          <li><strong><%= t('doc.comment.comment_reply.private.term') %></strong>: <%= t('doc.comment.comment_reply.private.meaning') %></li>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="field">
    <div class="textarea"><%= form.text_area(:markdown, :rows => 8, :cols => 70) %></div>
  </div>
  <div class="actions">
    <% if parent.is_a?(Comment) %>
      <%= link_to(t('cancel'), new_comment_path, :class => "cancel", 'data-form-id' => "reply_form_#{parent.id}", 'data-link-id' => "reply_link_#{parent.id}") %>
    <% end %>
    <% if parent.is_a?(Comment) %>
      <%= form.submit(t('save')) %>
    <% else %>
      <%= form.submit(t('reply')) %>
    <% end %>
  </div>
<% end %>