config/routes.rb
Paper::Application.routes.draw do
  
  namespace :admin do 
    resources :users
    resources :galleries do
      member { post :reindex }
    end
  end

  resources :posts do
    member { post :publish }
  end
  
  resources :images
  resources :comments

  devise_for :users, :controllers => { :registrations => "accounts" }
  
  devise_scope :user do
    get    "/signup" => "accounts#new",             :as => :signup
    get    "/login"  => "devise/sessions#new",      :as => :login
    delete "/logout" => "devise/sessions#destroy",  :as => :logout
  end
  
  root :to => "posts#index"
end

app/views/shared/_header.html.erb
<div id="header">
  <% if notice %>
    <div class="notice">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert">
      <%= alert %>
    </div>
  <% end %>
  <div class="name">
  <%= Paper.config.name %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="link">
  <%= link_to(t('home'), root_path) %>
</div>
<div class="user">
  <% if user_signed_in? %>
    <div class="name"><%= current_user.name %></div>
    <div class="edit">(<%= link_to(t('devise.accounts.edit'), edit_user_registration_path) %>)</div>
    <% if current_user.has_role?(:write_posts) %>
      <%= link_to_unless_current(t('new'), new_post_path) %><br />
    <% end %>
    <% if current_user.has_role?(:admin_users) %>
      <%= link_to_unless_current(t('admin.users.link'), admin_users_path) %><br />
    <% end %>
    <% if current_user.has_role?(:admin_galleries) %>
      <%= link_to_unless_current(t('admin.galleries.link'), admin_galleries_path) %><br />
    <% end %>
    <%= link_to(t('devise.sessions.sign_out'), logout_path, :method => :delete) %>
  <% else %>
    <%= link_to(t('devise.sessions.sign_in'), login_path) %>
    <br />
    <%= link_to(t('devise.accounts.sign_up'), signup_path) %>
  <% end %>
</div>